#!/bin/bash
echo "🚀 Deploy Manual para Lify"
echo "=========================="
echo ""
echo "1. Acesse: https://lify.com.br"
echo "2. Faça login na sua conta"
echo "3. Selecione o projeto: atendeai-lify-admin"
echo "4. Vá para a seção de configurações"
echo "5. Configure as variáveis de ambiente:"
echo ""
echo "VITE_WHATSAPP_SERVER_URL=https://atendeai-backend-production.up.railway.app"
echo "VITE_BACKEND_URL=https://atendeai-backend-production.up.railway.app"
echo ""
echo "6. Faça upload da pasta dist/"
echo "7. Clique em 'Deploy' ou 'Force Deploy'"
echo "8. Aguarde alguns minutos"
echo ""
echo "✅ Deploy concluído!"
