#!/bin/bash

echo "🚀 COMANDOS PARA EXECUTAR NA VPS"
echo "================================="
echo ""
echo "1. Conecte na VPS:"
echo "   ssh root@atendeai-backend-production.up.railway.app"
echo ""
echo "2. Navegue para o diretório:"
echo "   cd /root/atendeai-lify-backend"
echo ""
echo "3. Verifique se os arquivos foram copiados:"
echo "   ls -la .env.production.unified apply-fix-on-vps.sh"
echo ""
echo "4. Torne o script executável:"
echo "   chmod +x apply-fix-on-vps.sh"
echo ""
echo "5. Execute a correção:"
echo "   ./apply-fix-on-vps.sh"
echo ""
echo "6. Teste o webhook:"
echo "   curl -X POST http://localhost:3001/webhook/whatsapp-meta \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"entry\":[{\"changes\":[{\"value\":{\"messages\":[{\"from\":\"5511999999999\",\"text\":{\"body\":\"teste\"}}]}}]}]}'"
echo ""
echo "7. Teste o health check:"
echo "   curl -s http://localhost:3001/health"
echo ""
echo "8. Verifique os logs:"
echo "   pm2 logs atendeai-backend"
echo ""
echo "9. Teste enviando uma mensagem no WhatsApp"
echo ""
echo "✅ Após executar esses comandos, o WhatsApp deve voltar a funcionar!" 