#!/bin/bash

echo "🔧 CORRIGINDO INTEGRAÇÃO COM WHATSAPP"
echo "======================================"

echo ""
echo "📋 O problema é que o webhook processa a mensagem mas não envia a resposta para o WhatsApp."
echo "Vou criar uma versão que integra com a API do WhatsApp Meta."
echo ""

echo "🔗 Execute estes comandos na VPS:"
echo ""

echo "1️⃣ Parar o servidor atual:"
echo "   pm2 stop atendeai-backend"
echo ""

echo "2️⃣ Criar nova versão do servidor com integração WhatsApp:"
echo "   cat > server.js << 'EOF'"
echo "const express = require('express');"
echo "const cors = require('cors');"
echo "const axios = require('axios');"
echo "require('dotenv').config();"
echo ""
echo "const app = express();"
echo "const PORT = process.env.PORT || 3001;"
echo ""
echo "app.use(cors());"
echo "app.use(express.json());"
echo ""
echo "// Função para enviar mensagem via WhatsApp"
echo "async function sendWhatsAppMessage(to, message) {"
echo "  try {"
echo "    const response = await axios.post("
echo "      \`https://graph.facebook.com/v18.0/\${process.env.WHATSAPP_META_PHONE_NUMBER_ID}/messages\`,"
echo "      {"
echo "        messaging_product: 'whatsapp',"
echo "        to: to,"
echo "        type: 'text',"
echo "        text: { body: message }"
echo "      },"
echo "      {"
echo "        headers: {"
echo "          'Authorization': \`Bearer \${process.env.WHATSAPP_META_ACCESS_TOKEN}\`,"
echo "          'Content-Type': 'application/json'"
echo "        }"
echo "      }"
echo "    );"
echo "    console.log('Mensagem enviada:', response.data);"
echo "    return response.data;"
echo "  } catch (error) {"
echo "    console.error('Erro ao enviar mensagem:', error.response?.data || error.message);"
echo "    return null;"
echo "  }"
echo "}"
echo ""
echo "// Health check"
echo "app.get('/health', (req, res) => {"
echo "  res.json({"
echo "    status: 'OK',"
echo "    timestamp: new Date().toISOString(),"
echo "    uptime: process.uptime(),"
echo "    environment: process.env.NODE_ENV || 'development'"
echo "  });"
echo "});"
echo ""
echo "// Webhook para WhatsApp"
echo "app.post('/webhook/whatsapp-meta', async (req, res) => {"
echo "  try {"
echo "    console.log('[Webhook] Mensagem recebida:', req.body);"
echo ""
echo "    // Verificar se é um desafio de verificação"
echo "    if (req.body.mode === 'subscribe' && req.body['hub.challenge']) {"
echo "      console.log('[Webhook] Respondendo ao desafio de verificação');"
echo "      return res.status(200).send(req.body['hub.challenge']);"
echo "    }"
echo ""
echo "    // Processar mensagens"
echo "    if (req.body.entry && req.body.entry.length > 0) {"
echo "      let userMessage = '';"
echo "      let userPhone = '';"
echo ""
echo "      for (const entry of req.body.entry) {"
echo "        if (entry.changes && entry.changes.length > 0) {"
echo "          for (const change of entry.changes) {"
echo "            if (change.value && change.value.messages) {"
echo "              for (const message of change.value.messages) {"
echo "                if (message.type === 'text') {"
echo "                  userMessage = message.text.body;"
echo "                  userPhone = message.from;"
echo "                  break;"
echo "                }"
echo "              }"
echo "            }"
echo "          }"
echo "        }"
echo "      }"
echo ""
echo "      if (userMessage && userPhone) {"
echo "        console.log(\`[Webhook] Processando: \"\${userMessage}\" de \${userPhone}\`);"
echo ""
echo "        // Gerar resposta AI"
echo "        const responses = ["
echo "          'Olá! Como posso ajudá-lo hoje?',"
echo "          'Oi! Em que posso ser útil?',"
echo "          'Olá! Estou aqui para ajudar. O que você precisa?',"
echo "          'Oi! Como posso te auxiliar?',"
echo "          'Olá! Em que posso te ajudar hoje?'"
echo "        ];"
echo "        const aiResponse = responses[Math.floor(Math.random() * responses.length)];"
echo ""
echo "        console.log('[Webhook] Resposta AI:', aiResponse);"
echo ""
echo "        // Enviar resposta via WhatsApp"
echo "        const sendResult = await sendWhatsAppMessage(userPhone, aiResponse);"
echo ""
echo "        if (sendResult) {"
echo "          console.log('[Webhook] Resposta enviada com sucesso');"
echo "          return res.status(200).json({"
echo "            success: true,"
echo "            message: 'Webhook processado e resposta enviada',"
echo "            aiResponse: aiResponse,"
echo "            sendResult: sendResult"
echo "          });"
echo "        } else {"
echo "          console.error('[Webhook] Erro ao enviar resposta');"
echo "          return res.status(500).json({"
echo "            success: false,"
echo "            error: 'Erro ao enviar resposta via WhatsApp'"
echo "          });"
echo "        }"
echo "      }"
echo "    }"
echo ""
echo "    return res.status(200).json({"
echo "      success: true,"
echo "      message: 'Webhook recebido'"
echo "    });"
echo ""
echo "  } catch (error) {"
echo "    console.error('[Webhook] Erro:', error.message);"
echo "    return res.status(500).json({"
echo "      success: false,"
echo "      error: error.message"
echo "    });"
echo "  }"
echo "});"
echo ""
echo "// Rota de teste"
echo "app.get('/webhook/whatsapp-meta/test', (req, res) => {"
echo "  res.json({"
echo "    success: true,"
echo "    message: 'Webhook WhatsApp funcionando',"
echo "    timestamp: new Date().toISOString()"
echo "  });"
echo "});"
echo ""
echo "app.listen(PORT, () => {"
echo "  console.log(\`🚀 Servidor rodando na porta \${PORT}\`);"
echo "  console.log(\`📱 Webhook: http://localhost:\${PORT}/webhook/whatsapp-meta\`);"
echo "  console.log(\`🌍 Ambiente: \${process.env.NODE_ENV || 'development'}\`);"
echo "});"
echo "EOF"
echo ""

echo "3️⃣ Reiniciar o servidor:"
echo "   pm2 restart atendeai-backend"
echo ""

echo "4️⃣ Testar o webhook:"
echo "   curl http://localhost:3001/webhook/whatsapp-meta/test"
echo ""

echo "5️⃣ Ver logs para debug:"
echo "   pm2 logs atendeai-backend"
echo ""

echo "🎯 Após isso, o WhatsApp deve voltar a responder!"
echo ""
echo "📱 Teste enviando uma mensagem para o WhatsApp da clínica." 